### ISSUE TITLE
Not working on BigSur

### ISSUE THREAD

**Issue by shaunpatterson** [rodyager/RWTS-PDFwriter#24]
The directory it creates isn't a directory:

```
-rw-r--r--@   1 shaunpatterson  staff     18436 Dec 27 04:21 .DS_Store
drwxr-xr-x+ 310 shaunpatterson  staff      9920 Dec 27 04:29 ..
drwxr-xr-x   75 shaunpatterson  staff      2400 Dec 27 04:48 .
-rw-r--r--@   1 shaunpatterson  staff       876 Dec 27 04:48 PDFWriter
```

If I delete this then create it manually with `mkdir ~/Documents/PDFWriter` it still doesn't work.  Printing from TextEdit yields nothing in this directory.  

```
Darwin jalapeno.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

**Comment by shaunpatterson** [comment]
Well, the files are actually going to the spool directory:

```
/var/spool/pdfwriter/shaunpatterson

shaunpatterson@jalapeno/v/s/p/shaunpatterson> ls -ltra
total 1136
drwxr-xr-x  3 root            wheel     96 Dec 27 04:19 ..
-rw-rw-rw-@ 1 root            wheel      0 Dec 27 04:19 Icon?
-rw-------@ 1 shaunpatterson  staff  20343 Dec 27 04:19 Untitled 2.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:23 Untitled 2-1.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:25 Untitled 2-2.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:27 Untitled 2-3.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:36 Untitled 2-4.pdf
drwx------@ 9 shaunpatterson  staff    288 Dec 27 04:57 .
-rw-------@ 1 shaunpatterson  staff  47630 Dec 27 04:57 Untitled.pdf
```

**Comment by rodyager** [comment]
That’s because the “directory” it creates is a symbolic link to the actual location.

The actual location is where it is because the operating system tightly limits the locations to which printer drivers can write files as part of a “print” operation.

Rod

Sent from my iPhone

On 27 Dec 2022, at 8:59 pm, Shaun Patterson ***@***.***> wrote:

﻿

Well, the files are actually going to the spool directory:

/var/spool/pdfwriter/shaunpatterson

***@***.***/v/s/p/shaunpatterson> ls -ltra
total 1136
drwxr-xr-x  3 root            wheel     96 Dec 27 04:19 ..
-rw-rw-rw-@ 1 root            wheel      0 Dec 27 04:19 Icon?
-rw-------@ 1 shaunpatterson  staff  20343 Dec 27 04:19 Untitled 2.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:23 Untitled 2-1.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:25 Untitled 2-2.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:27 Untitled 2-3.pdf
-rw-------  1 shaunpatterson  staff  20343 Dec 27 04:36 Untitled 2-4.pdf
drwx------@ 9 shaunpatterson  staff    288 Dec 27 04:57 .
-rw-------@ 1 shaunpatterson  staff  47630 Dec 27 04:57 Untitled.pdf

**Comment by shaunpatterson** [comment]
Hmm, it's not a symbolic link.

**Comment by rodyager** [comment]
You are correct. Its a MacOS alias that points to /private/var/spool/pdfwriter/xxx

where xxx is whatever NSUserName() returns for the current user.

The easiest way to reveal the target location is to use Finder’s Info.

let theOrigURL = NSURL.fileURL(withPath: "/private/var/spool/pdfwriter/\(NSUserName())")

       let theData = try! theOrigURL.bookmarkData(options: [URL.BookmarkCreationOptions.suitableForBookmarkFile],

    includingResourceValuesForKeys: nil,

  relativeTo: nil)

       try! URL.writeBookmarkData(theData, to:panel.url!)

Rod



On 28 Dec 2022, at 8:53 am, Shaun Patterson ***@***.***> wrote:



Hmm, it's not a symbolic link.
