### ISSUE TITLE
The installation failed

### ISSUE THREAD

**Issue by jimmyangel** [rodyager/RWTS-PDFwriter#33]
It goes through the install but unfortunately it is not successful.

I am running macOS Catalina 10.15.7.

I tried installing from the command line but Utility does not seem to get installed.

**Comment by rodyager** [comment]
Reasonably certain that if the installer says it has succeeded, the Utility has been installed.

Did you read the read me at https://github.com/rodyager/RWTS-PDFwriter which has instructions on how to open the Utility?

But if you want to find it, it is located in /Library/Printers/RWTS/Utilities/

(That location is one of the few locations that can be opened from the Utility tab in the Printer preference pane)

Rod

Sent from my iPhone

On 28 Feb 2023, at 12:50 pm, Ricardo Morin ***@***.***> wrote:

﻿

It goes through the install but unfortunately it is not successful.

I am running macOS Catalina 10.15.7.

I tried installing from the command line but Utility does not seem to get installed.

**Comment by jimmyangel** [comment]
Sorry, it looks like I did not make myself clear. The install goes through until the end when it says "An error occurred during installation" and a warning sign saying "The installation failed." After install there is no /Library/Printers/RWTS/Utilities/

Thanks,

Ricardo

**Comment by jimmyangel** [comment]
Here is the log...

[Installer Log 27-Feb-2023.txt](https://github.com/rodyager/RWTS-PDFwriter/files/10846205/Installer.Log.27-Feb-2023.txt)

Thank you,

Ricardo

**Comment by rodyager** [comment]
Thanks. Have you previously installed this on the machine, or did you build the Utility from the source code on github.

If so, it is possible (but its not supposed to happen) that the installer relocated the installation of the Utility so that it updated the version already present on your machine (in whatever location it is currently found in.) That would at least account for your report that
/Library/Printers/RWTS/Utilities/ not existing and would explain the error found in the log.

./postinstall: LSOpenURLsWithRole() failed with error -10825 for the file /Library/Printers/RWTS/Utilities/PDFWriter Utility.app.

If I’m right, the solution is to delete the mislocated copy of PDFWriter Utility and rerun the installer.

Rod







On 28 Feb 2023, at 2:13 pm, Ricardo Morin ***@***.***> wrote:



Here is the log...

Installer Log 27-Feb-2023.txt<https://github.com/rodyager/RWTS-PDFwriter/files/10846205/Installer.Log.27-Feb-2023.txt>

Thank you,

Ricardo

**Comment by jimmyangel** [comment]
I found the PDFWriter Utility under /Library/Printers/RWTS/Utilities. I went ahead and deleted it and reran the installer. Same result.

I tried to run the PDFWriter Utility.app, but i got the following message: 

> **You can’t use this version of the application “PDFWriter Utility.app” with this version of macOS.**
> You have macOS 10.15.7. The application requires macOS 11.0 or later.

Thanks,

Ricardo

**Comment by rodyager** [comment]
Thanks. That makes sense. I’ve required at least MacOS 11 for quite a while.

I think Version 2.0 was MacOS 10.11+ compatible. If so, it would work for you and the functional differences are quite minor (even though  absolutely everything has been rewritten since then.)

You can download it from

https://github.com/rodyager/RWTS-PDFwriter/releases/tag/v2.0

Rod

On 28 Feb 2023, at 2:51 pm, Ricardo Morin ***@***.***> wrote:



I found the PDFWriter Utility under /Library/Printers/RWTS/Utilities. I went ahead and deleted it and reran the installer. Same result.

I tried to run the PDFWriter Utility.app, but i got the following message:

You can’t use this version of the application “PDFWriter Utility.app” with this version of macOS.
You have macOS 10.15.7. The application requires macOS 11.0 or later.

Thanks,

Ricardo

**Comment by jimmyangel** [comment]
That's weird, I installed version 2, after deleting the PDFWriter Utility.app. This time the installer says that the installation was successful, but I still cannot run the utility as I get the same "You have macOS 10.15.7. The application requires macOS 11.0 or later." error.

**Comment by jimmyangel** [comment]
I went back to version 1.01, and that seems to work ok. Of course, there is no utility :)

**Comment by rodyager** [comment]
Yeah. I’m tracking back through my code. It looks as though the earliest version of the Utility started life already assuming MacOS 11.

Rod

On 28 Feb 2023, at 3:48 pm, Ricardo Morin ***@***.***> wrote:



I went back to version 1.01, and that seems to work ok. Of course, there is no utility :)

**Comment by andrea1984** [comment]
So there will be an updated version for running the utility with macos 10.15?

**Comment by rodyager** [comment]
Not imminently. The utility is written in SwiftUI and I couldn’t quickly find he necessary modifications to make it run under the app lifecycle required in MacOS10.15. Given the tiny proportion of users using 10.15 and the fact that I’d have to rewrite other bits of code to go below 10.15.4, I’m not sure it’s worth the effort to fill this small niche.

The last of the 1.x series is completely functional, and if you want the “choose my own location” feature, the simple thing to do is to create an alias of /Users/Shared/PDFwriter/<your user name> in the location of your choice. (That’s effectively what the Utility does).

Rod

Sent from my iPhone

On 3 Mar 2023, at 7:35 am, andrea1984 ***@***.***> wrote:

﻿

So there will be an updated version for running the utility with macos 10.15?

**Comment by b27lu** [comment]
I'm using MacOS 10.15.7 as well and the version 1.0.1 works for me! (MacOS 10.15.7 is the last version that supports my iMac :)
