### ISSUE TITLE
PDF Writer does not work

### ISSUE THREAD

**Issue by classof77** [rodyager/RWTS-PDFwriter#37]
iMac late 2012 
Ventura 13.5
Photoshop 2022

Want to print a PDF via PDFWriter.
The Document is an .psb-File with 3005mm x 505mm.

When i press the "Print"-Button the Photoshop-Print-Preferences-Window 
disappears but nothing happens...

Thank you.

**Comment by rodyager** [comment]
Did you check in the destination folder? Creating a pdf via pdf writer from Photoshop with Ventura 13.5 is working for me.

Rod

Sent from my iPhone

On 5 Aug 2023, at 7:37 pm, classof77 ***@***.***> wrote:

﻿

iMac late 2012
Ventura 13.5
Photoshop 2022

Want to print a PDF via PDFWriter.
The Document is an .psb-File with 3005mm x 505mm.

When i press the "Print"-Button nothing happens...

Thank you.

**Comment by rodyager** [comment]
Here’s a 3005 mm x 505 mm pdf created from Photoshop via pdfWriter.

Part of the trick is to use Print Settings in Photoshops print menu, select paper size, select custom and create a custom paper size that is 3005 mm x 505 mm. Then use your custom paper size when you print.

Printing warned me that it was cropping because the “paper” was not large enough. I think that you may need to have the “paper” a little larger than the image, but you can experiment.

Rod

**Comment by classof77** [comment]
Hello, that was quick. Many thanks for the quick response.
I proceeded exactly as you described. Anyway, somehow it didn't accept the print settings at the beginning. After I switched the color management from printer to Photoshop and back to printer, it suddenly took over and I was able to "print". :)
So in the end it worked. Thank you for your help and have a nice Sunday.
