### ISSUE TITLE
Pdfx3 compliant

### ISSUE THREAD

**Issue by JeroenSteen** [rodyager/RWTS-PDFwriter#39]
Is the PDF output of this Mac-printdriver PDFX3 compliant, so that it can handle transparancies and layers correctly?

**Comment by rodyager** [comment]
The output of PDFwriter is exactly what the OS would deliver to a printer that accepted PDF input. All it does is trick the OS into thinking that is what it is doing and captures the output stream.

Consequently, the output has the same features/limitations as the save as pdf option in the print dialog for an ordinary printer.

Rod

Sent from my iPhone

On 16 Sep 2023, at 6:31 am, Jeroen ***@***.***> wrote:

﻿

Is the PDF output of this Mac-printdriver PDFX3 compliant, so that it can handle transparancies and layers correctly?
