### ISSUE TITLE
Output help

### ISSUE THREAD

**Issue by kilatepro** [rodyager/RWTS-PDFwriter#6]
Hi,
Doesn’t the PDFWriter print CMYK mode PDFs?
The screen output seems in very low resolution, specially the fonts. Will it print in low resolution??

Thank you.

(MacOS Mojave)

**Comment by rodyager** [comment]
PDFWriter will create a pdf that looks exactly the same as macOS would print to a generic postscript laser printer.

All it does is to take the pdf that macOS would ordinarily have sent to the printer and capture it as a file.

It’s only real use is for  software that allows printing, but prevents the "Save as pdf" button from appearing in the print dialog.


Rod


On 1 Jul 2020, at 2:58 pm, Gabriela Favre <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,
Doesn’t the PDFWriter print CMYK mode PDFs?
The screen output seems in very low resolution, specially the fonts. Will it print in low resolution??

Thank you.

**Comment by kilatepro** [comment]
But why do the fonts and arts (curves) look so serrated? I am printing from Indesign, using FontExplorerPro. Everything is ok. If I create a PDF from Indesign direclty, it won’t look like that.
I need to use PDFWriter because I need to create a PDF that’s 85% the original page size, and Indesign dialog does not give me that option.

And why does it only accept RGB colors??

**Comment by rodyager** [comment]
The solution to your particular problem is to select the postscript file option at the top of Indesign’s printer choices.
You’ll need to choose the save location and make sure you use .ps as the file extension.
The resulting postscript file can be opened in Preview, and from there you can save it as a pdf.

Rod

On 1 Jul 2020, at 3:29 pm, Gabriela Favre <notifications@github.com<mailto:notifications@github.com>> wrote:



But why do the fonts and arts (curves) look so serrated? I am printing from Indesign, using FontExplorerPro. Everything is ok. If I create a PDF from Indesign direclty, it won’t look like that.
I need to use PDFWriter because I need to create a PDF that’s 85% the original page size, and Indesign dialog does not give me that option.

And why does it only accept RGB colors??

**Comment by rodyager** [comment]
Actually, the better advice would be to save as a pdf from Indesign (using the export menu).

Open the pdf you get in Preview and use Preview’s print dialog to set the scaling to 85% and then chose Preview’s save to pdf option.

Rod

On 1 Jul 2020, at 3:29 pm, Gabriela Favre <notifications@github.com<mailto:notifications@github.com>> wrote:



But why do the fonts and arts (curves) look so serrated? I am printing from Indesign, using FontExplorerPro. Everything is ok. If I create a PDF from Indesign direclty, it won’t look like that.
I need to use PDFWriter because I need to create a PDF that’s 85% the original page size, and Indesign dialog does not give me that option.

And why does it only accept RGB colors??

**Comment by kilatepro** [comment]
Hi Rod.
Thank you very much!! Thank was perfect. It would be much easier if Adobe gave more professional print to PDF options.
But your solutoin is perfect, after a hard effort of search!!

Best regards.

**Comment by kilatepro** [comment]
Hi Rod.
I finally found another workaround which was very good too.

https://indesignsecrets.com/creating-a-different-size-print-pdf-a-workaround.php

**Comment by kilatepro** [comment]
Hi Rod.
I finally found another workaround which was very good too.

https://indesignsecrets.com/creating-a-different-size-print-pdf-a-workaround.php
